# Generated by Django 5.0.6 on 2024-07-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voornaam', models.CharField(max_length=50)),
                ('achternaam', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('aantal_pers', models.IntegerField()),
                ('res_date', models.DateTimeField(verbose_name='Reservation date')),
            ],
        ),
    ]
