# Generated by Django 5.0.6 on 2024-07-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_reservatie'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservatie',
            name='res_time',
            field=models.TimeField(default=(0, 0)),
        ),
        migrations.AlterField(
            model_name='reservatie',
            name='res_date',
            field=models.DateField(verbose_name='Reservation date'),
        ),
    ]
