# Generated by Django 5.0.6 on 2024-07-01 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_reservatie_res_time_alter_reservatie_res_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservatie',
            name='res_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservatie',
            name='res_time',
            field=models.TimeField(default=datetime.time(6, 0)),
        ),
    ]
