# Generated by Django 5.0.6 on 2024-07-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_reservatie_res_date_alter_reservatie_res_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservatie',
            name='res_time',
            field=models.TimeField(default='00:00'),
        ),
    ]
