# Generated by Django 5.0.6 on 2024-07-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_reservatie_res_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservatie',
            name='res_time',
            field=models.TimeField(),
        ),
    ]
